### ISSUE TITLE
What about Strings and &str?

### ISSUE THREAD

**Issue by ShayBox** [bytedream/serde-inline-default#1]
It seems this doesn't work for `&str` and `String`, `try using a conversion method` but nothing parses correctly (into, to_string, to_owned, String::from)

**Comment by bytedream** [comment]
Can you provide an example how it isn't working?
I've just added some example files and string conversion should work when done like [this](https://github.com/ByteDream/serde-inline-default/blob/b0489edfafde8893b099688b6ecc917eab435107/examples/basic.rs#L9-L10).

**Comment by ShayBox** [comment]
I guess it does work, I must have been doing something wrong yesterday, it always said mismatched types, try using conversion method.

**Comment by rochacbruno** [comment]
It is not working when there is a lifetime


```rust
#[serde_inline_default]
#[derive(Debug, Deserialize, Serialize)]
#[serde(rename_all = "lowercase")]
struct Person<'a> {
    #[serde_inline_default("A name")]
    name: &'a str,
}
```

```
error[E0261]: use of undeclared lifetime name `'a`
  --> src/main.rs:36:12
   |
31 | #[serde_inline_default]
   |                        - lifetime `'a` is missing in item created through this procedural macro
...
36 |     name: &'a str,
   |            ^^ undeclared lifetime

```
