### ISSUE TITLE
Not working with non static lifetime

### ISSUE THREAD

**Issue by bytedream** [bytedream/serde-inline-default#6]
It is not working when there is a lifetime

```rust
#[serde_inline_default]
#[derive(Debug, Deserialize, Serialize)]
#[serde(rename_all = "lowercase")]
struct Person<'a> {
    #[serde_inline_default("A name")]
    name: &'a str,
}
```

```
error[E0261]: use of undeclared lifetime name `'a`
  --> src/main.rs:36:12
   |
31 | #[serde_inline_default]
   |                        - lifetime `'a` is missing in item created through this procedural macro
...
36 |     name: &'a str,
   |            ^^ undeclared lifetime

```

_Originally posted by @rochacbruno in https://github.com/bytedream/serde-inline-default/issues/1#issuecomment-2411703117_

**Comment by bytedream** [comment]
@rochacbruno creating a default for a reference is generally not supported in serde afaik. You'd have to use `Cow<'a, str>` instead of `&'a str`, support for lifetimes in generic arguments got added in [v0.2.2](https://github.com/bytedream/serde-inline-default/releases/tag/v0.2.2).

**Comment by rochacbruno** [comment]
Hi @bytedream, this works

```rust

fn default_name() -> &'static str {
    "My Site"
}

#[derive(Debug, Deserialize, Serialize)]
#[serde(rename_all = "lowercase")]
struct Site<'a> {
    #[serde(default = "default_name")]
    name: &'a str,
}
```

**Comment by bytedream** [comment]
Okay that's a bit weird, yesterday evening I had a similar example and it didn't compile haha, but yours does so all good.
v0.2.2 also has support for lifetimes references, so using at least this version should fix your problem.
