### ISSUE TITLE
Looks like the order of attributes matters

### ISSUE THREAD

**Issue by SteveLauC** [bytedream/serde-inline-default#8]
Hi, thanks for this neat crate!

I just found it that if you write it in this way, then it would work:

```rust
#[serde_inline_default]
#[derive(Deserialize)]
struct Foo
```

but this won't:

```rust
#[derive(Deserialize)]
#[serde_inline_default]
struct Foo
```

**Comment by bytedream** [comment]
This is known and can't be changed. `#[serde_inline_default]` internally generates functions and specific attributes which must be in place before `#[derive(Deserialize)]` executes because it depends on the generated items

**Comment by SteveLauC** [comment]
That makes sense, I just found that it is documented in README, sorry for opening this issue!
